### ISSUE TITLE
BC7010 Signs also affects Updater

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#38]
hi, 
the BC7010 signs also affect updaters, so its a bit bothersome to update regions in a world that has an own player inventory.

because i have to place an BC7010 under the rails, so a player gets to the destination in the new world, while the updater gets that ticket aswell, and then stops updating and goes to the adress instead.

im having to remove every singel BC7010 sign (and i have quite a few below tracks) when i want to update the track routing..

can you please correct this?

thanks.

**Comment by catageek** [comment]
Hi,

Can you try [this](http://bytecart.catageek.info/maven/repositories/releases/com/github/catageek/ByteCart/2.9.4/ByteCart-2.9.4.jar) and tell me if it's OK ?

Thx

**Comment by thiefa** [comment]
hi, 
just put it on the server. works like a charm!
thank you so mutch :)

i did a little donation, you did so mutch allready for my server with that plugin.. was about high-time ;)

thanks again :)

**Comment by catageek** [comment]
You're welcome. Thanks for the donation: it is the first one !
