### ISSUE TITLE
Images of how-to guides are missing

### ISSUE THREAD

**Issue by ShadowJonathan** [catageek/ByteCart#39]
The current how-to guides in the wiki are faulty, there are no pictures present to explain the set-up and construction of both the router and the 5-cart station:

https://github.com/catageek/ByteCart/wiki/Howto-:-Build-a-router

https://github.com/catageek/ByteCart/wiki/Howto-:-A-station-for-5-cart-trains

It would be appreciated if you'd update the images, or re-explain the construction of these constructions with words, as me and some other people want to experiment with designs, and we need to start somewhere.

**Comment by ShadowJonathan** [comment]
Update; seems like some other images are missing as well, like the 3-step tutorial to making a network:

[Step 1 page](https://github.com/catageek/ByteCart/wiki/Step-1-:-A-simple-circular-line)

[Step 2 page](https://github.com/catageek/ByteCart/wiki/Step-2-:-Connect-rings-together)

[Step 3 page](https://github.com/catageek/ByteCart/wiki/Step-3-:-Expand-you-network)

**Comment by thiefa** [comment]
hi, 
yep i agree on missing images!

however, as for the tutorial, i personally prefered to download the tut world catageek made, to look at it.. some stuff is quite difficult and describing it (even with pictures) takes a ton of pages...

Tut-World download link: [http://catageek.free.fr/bytecart/]



if you need further help, we can have a look at my server if you want..

**Comment by ShadowJonathan** [comment]
I havent seen that link yet, thank you so much for posting that, now i can take a look at some stuff.

That looks very interesting, ill sure take a closer look at home, when i have access to my computer.

**Comment by catageek** [comment]
Hi all,

Thanks for the report. I used to host them in Imageshack but they closed their free image hosting service to accept only premium users (money is money).

Unfortunately I have no backup of the images and no immediate plan to remake the snapshots. I hope that the link given by @thiefa will help you. @thiefa has also a wonderful map to visit to see Bytecart in action.

I will fix this when I have some time to spend on my server.

**Comment by ShadowJonathan** [comment]
Thank you so much for responding, one tiny thing, the updaters on the minecraft network map you made crazing out, it might need an update and a total reset.

I tried sending a updater cart to region 4, and the cart got stuck between the backbone router and the region plug-in router, there are more cases of this, but this is the most notable one.

**Comment by ShadowJonathan** [comment]
@thiefa is there any way you can PM me the IP to your server? I wanna see the map.

**Comment by thiefa** [comment]
hi, 
sure thing.
well, duno how to pm here, so i leave the adresse just here...

i home-host  on:
pia.hopto.org:25566

**Comment by ShadowJonathan** [comment]
Thanks, ill probably join in approximately 18 hours from now, but thank you for the IP, only please make sure to set the right bytecart permissions for people who just join.
