### ISSUE TITLE
Something to fix if you update to 1.11.2 "exception while executing task 8"

### ISSUE THREAD

**Issue by ardentcrest** [catageek/ByteCart#44]
01:22:06 [WARNING] [ByteCart] Plugin ByteCart v2.9.4 generated an exception while executing task 8
01:22:06 java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
01:22:06 	at org.mcstats.MetricsLite.postPlugin(MetricsLite.java:287) ~[?:?]
01:22:07 	at org.mcstats.MetricsLite.access$200(MetricsLite.java:53) ~[?:?]
01:22:07 	at org.mcstats.MetricsLite$1.run(MetricsLite.java:175) ~[?:?]
01:22:07 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.11.2.jar:git-Bukkit-46226d6]
01:22:07 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.11.2.jar:git-Bukkit-46226d6]
01:22:07 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
01:22:07 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
01:22:07 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by ardentcrest** [comment]
please update to 1.11.2

**Comment by catageek** [comment]
Hello,
Please disable the metrics plugin by setting 'metrics = false' in the config file.
I will remove entirely the metrics plugin in the next release.

**Comment by ardentcrest** [comment]
Thanks that worked.

Question. could there be a way to use the trains from the Vehicles (No resourcepacks needed!) plugin with ByteCart. As it would be nice to be in something that looks like a train when going from station to station :D

**Comment by catageek** [comment]
I really don't know. I looked at the plugin page and the source code is private. Maybe you should ask in the Vehicles user forum.
