### ISSUE TITLE
anticollision and another

### ISSUE THREAD

**Issue by ardentcrest** [catageek/ByteCart#46]
I dont know if its me. but when a cart or train is leaving a station and another is about to pass the ones coming out of the station stop ( i know this is the anticollision ) but they do not move again at all, they also can not be moved in any way, it is like they are stuck to the track.

also on the smaller stations if I try to put 4 carts together to make a train they start off before I can give the first one a ticket

**Comment by catageek** [comment]
For anticollision issue, tell me the position in your server where I can see what is going on, I will connect later.

For the trains, you have the choice between TrainCarts plugin to make them simple, or to use the complicated train management of ByteCart. you can use a BC7001 chain to stop the carts individually. I advise you to use Traincarts. Traincarts trains are compatible with ByteCart and solve many issues you can have without it.

**Comment by ardentcrest** [comment]
my server is at delos.zapto.org:25565 world a. Could be laggy, my up load speed has gone to shit lately
and traincarts does not work in 1.11.2 (has not been updated since 1.8.4 - 1.9)

**Comment by ardentcrest** [comment]
when i moved the chestcart

20:50:34 [SEVERE] **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
20:50:34 Could not pass event VehicleCreateEvent to ByteCart v2.9.4
20:50:34 org.bukkit.event.EventException
20:50:34 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
20:50:34 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at us.Myles.PWP.TransparentListeners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:30) [PerWorldPlugins.jar:?]
20:50:34 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.<init>(EntityMinecartAbstract.java:114) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.EntityMinecartContainer.<init>(EntityMinecartContainer.java:64) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.EntityMinecartChest.<init>(SourceFile:24) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.EntityMinecartAbstract.a(EntityMinecartAbstract.java:55) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.ItemMinecart.a(ItemMinecart.java:114) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.ItemStack.placeItem(ItemStack.java:160) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:491) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
20:50:34 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
20:50:34 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:34 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
20:50:35 Caused by: java.lang.NullPointerException
20:50:35 	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.getContents(CraftInventory.java:66) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.getStorageContents(CraftInventory.java:54) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.contains(CraftInventory.java:92) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.contains(CraftInventory.java:102) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
20:50:35 	at com.github.catageek.ByteCart.AddressLayer.Ticket.getTicketslot(Ticket.java:49) ~[?:?]
20:50:35 	at com.github.catageek.ByteCart.AddressLayer.AddressFactory.getAddress(AddressFactory.java:30) ~[?:?]
20:50:35 	at com.github.catageek.ByteCart.Signs.AbstractTriggeredSign.isTrain(AbstractTriggeredSign.java:109) ~[?:?]
20:50:35 	at com.github.catageek.ByteCart.Signs.BC7001.trigger(BC7001.java:79) ~[?:?]
20:50:35 	at com.github.catageek.ByteCart.EventManagement.ByteCartListener.onVehicleCreate(ByteCartListener.java:145) ~[?:?]
20:50:35 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
20:50:35 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
20:50:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
20:50:35 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
20:50:35 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
20:50:35 	... 24 more

**Comment by ardentcrest** [comment]
inter net goes up and down here going to viber next few weeks. I had two things i wanted to show you :)

**Comment by ardentcrest** [comment]
internet goes up and down here a lot. going to viber next few weeks. I had two things i wanted to show you :)

**Comment by catageek** [comment]
This is a bug in craftbukkit/spigot. It happens when you instantiate a cart directly on a BC sign. Thanks for reporting it

**Comment by ardentcrest** [comment]
did you ger much lag when you went to my server and do you have one.

**Comment by catageek** [comment]
I don't have a server and, yes, there was a lot of lag. I will see later when I connect if there is still lag.

**Comment by ardentcrest** [comment]
As train cart is no more. I needed a stop go station for a metro type line. I got it done with a station sign, a stop/start sign and a hopper timer :)

I would love to know if you are going to update bytecart, and what you hope to do with it.

**Comment by catageek** [comment]
I will update soon, and I only maintain the compatibility with MC versions since I don't play minecraft anymore and have not much interest in coding this plugin like 4 years ago.
Anyway there will be a Sponge version when Sponge will be more mature.
