### ISSUE TITLE
Things gone missing

### ISSUE THREAD

**Issue by ardentcrest** [catageek/ByteCart#48]
Hi, hope things are well.

I cant seem to fine your website or any info on bukket or spigot about the plugin. I also cant seem to find the world download.

I see you have done a bit of work so will there be a jar file I can download.

PS there will soon be a new version of Traincarts I'm testing it at the moment.

**Comment by catageek** [comment]
Hi,

Plugin page has moved to [Spigot](https://www.spigotmc.org/resources/bytecart.39493/). There will be a new version soon, I am currently updating the documentation.

You can download the new version [here](http://catageek.free.fr/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/) if you want to test it.
