### ISSUE TITLE
Selecting cart issue

### ISSUE THREAD

**Issue by itskun** [catageek/ByteCart#53]
So, how do I choose a cart, if the right click action is performed, for example, opens the chest.
I'm writing a command /sendto 1.1.2, then I have a message "Select a chest cart", right-clicking to a cart opens the chest...

**Comment by thiefa** [comment]
/sendto x.x.x  and then right clicking a cart works for me...
adds the ticket to the cart, and does not open the inv in the first place.

spigot 1.12.1 and latest bc

**Comment by catageek** [comment]
Only possible cause I see is that another plugin is cancelling the event of right-clicking before ByteCart can catch it.
Please search for the plugin that triggers this behaviour, to see if we can work on this issue

**Comment by itskun** [comment]
Okay, it remains to find out what kind of plugins are these.

**Comment by itskun** [comment]
I searched that Railcraft triggers this behaviour.
Thermos-1.7.10-1614-56-server.jar
Railcraft_1.7.10-9.12.2.0
ByteCart 2.7.5

**Comment by catageek** [comment]
I think I found the problematic line [here](https://github.com/Railcraft/Railcraft/blob/aba7703d2480073998c5a8a02ad2802362fefaba/src/main/java/mods/railcraft/common/fluids/CustomContainerHandler.java#L48)
The fix should be trivial and I will make a new release in a few days. In the meantime, you can use /mego and manually transfer the ticket from your inventory to the chest.

**Comment by catageek** [comment]
Hi @itskun 

Please download and try this [update](http://catageek.free.fr/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/3.1.3-SNAPSHOT/ByteCart-3.1.3-20171004.044301-1.jar)

**Comment by itskun** [comment]
Unfortunately, I can't check because I have 1.7.10 server.
