### ISSUE TITLE
Just wondering......

### ISSUE THREAD

**Issue by MrKiller01** [catageek/ByteCart#54]
Hi Catageek,

I was just wondering who complained at MD_5's adres about me harassing people. Was it the private messages or the almost nonstop updating error fabrication i planted online? It is to your knowledge that i was banned by that child, and he never gave me a reason as to why. Now i have premium material on spigotmc, which is inaccessible to me now, if it was your action, please reconsider change this for me, because i really hate a person who waves around with his own rules and not follow them if it comes to himself.
If you have absolutely no idea what i am talking here about, never mind then, but still a message to MD_5 from you people, the plugin developers, trying to make a small bit of money through the sale of those plugins, of which every banned person from SpigotMC.org is unable to participate, so costing the devs large amounts of potential money!!!!

Thanks very much...

Ps. I am trying newest bkcommonlib with bytecart, hope it will work this time....

**Comment by MrKiller01** [comment]
getting still errors, so, gonna unload it, again.... Shame...

**Comment by catageek** [comment]
I don't know what you are talking about. Clearly not my business.

**Comment by MrKiller01** [comment]
Thanks anyway for answering. But I still have errors using Bytecart.... Hope in the future we can have a chat about it...
